[workspace]
resolver = "2"
members = [
    "forc",
    "forc-pkg",
    "forc-plugins/forc-client",
    "forc-plugins/forc-doc",
    "forc-plugins/forc-fmt",
    "forc-plugins/forc-lsp",
    "forc-plugins/forc-tx",
    "forc-test",
    "forc-tracing",
    "forc-util",
    "scripts/mdbook-forc-documenter",
    "sway-ast",
    "sway-core",
    "sway-error",
    "sway-ir",
    "sway-ir/sway-ir-macros",
    "sway-lsp",
    "sway-parse",
    "sway-types",
    "sway-utils",
    "swayfmt",
    "test",
]
exclude = [
    "examples/*",
    "swayfmt/test_macros"
]

[profile.dev.package.sway-lsp]
debug = 2

[workspace.dependencies]
fuel-asm = "0.31"
fuel-crypto = "0.31"
fuel-types = "0.31"
fuel-tx = "0.31"
fuel-core-client = "0.18"
fuel-vm = "0.31"
fuels-core = "0.41"
fuels-accounts = "0.41"
fuels-types = "0.41"

[workspace.package]
edition = "2021"
authors = ["Fuel Labs <contact@fuel.sh>"]
homepage = "https://fuel.network/"
license = "Apache-2.0"
repository = "https://github.com/FuelLabs/sway"

[patch.crates-io]
fuels-core = { git = "https://github.com/FuelLabs/fuels-rs", branch = "feature/fuel-core-0.18" }
fuels-types = { git = "https://github.com/FuelLabs/fuels-rs", branch = "feature/fuel-core-0.18" }
fuels-accounts = { git = "https://github.com/FuelLabs/fuels-rs", branch = "feature/fuel-core-0.18" }
