[package]
name = "forc-lsp"
version = "0.47.0"
description = "A simple `forc` plugin for starting the sway language server."
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
tikv-jemallocator = "0.5.4"
sway-lsp = { version = "0.47.0", path = "../../sway-lsp" }
tokio = { version = "1.8" }
